package com.example.restservice;

import java.util.UUID; 

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;

import java.io.Serializable;


// domain
@Entity
public class Product implements Serializable{
    @Id
    @GeneratedValue
    Long IDI;//workaround to keep id generated by app.. todo

    UUID id;
    String name;
    double price;

    public Product() {
    }

    public Product(String name, double price) {
        this.name = name;
        this.price = price;
        this.id = UUID.randomUUID(); 
    }
    

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name ;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }


    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Long getIDI() {
        return this.IDI;
    }

    public void setIDI(Long IDI) {
        this.IDI = IDI;
    }

    @Override
    public String toString() {
        return "Product{" +
            " id='" + getId() + "'" +
            ", name='" + getName() + "'" +
            ", price='" + getPrice() + "'" +
            "}";
    }

}
